#:schema ./spells_schema.json

[[zauber]]
name = "Ablenkung"
schule = "Illusion"
stufe = 5
reichweite = "selbst"
klassen = [] # TODO  
beschreibung = [
  "Du wirst unsichtbar, gleichzeitig erscheint ein illusionäres Abbild von dir selbst dort, wo du stehst. Dieses Abbild bleibt für die Wirkungsdauer bestehen, aber die Unsichtbarkeit endet, wenn du angreifst oder einen Zauber wirkst.",
  "Als Aktion kannst du dein illusionäres Abbild bis zu deiner doppelten Bewegungsrate bewegen und es gestikulieren, sprechen und auf jede Art handeln lassen, die du möchtest.",
  "Du kannst durch seine Augen sehen und durch seine Ohren hören, als würdest du dort stehen, wo es sich aufhält",
  "In jedem deiner Züge kannst du als Bonusaktion von deinen Sinnen zu den Sinnen des Abbilds wechseln und andersherum. Solange du seine Sinne nutzt, bist du blind und taub für deine eigene Umgebung",
]
gesten = true
konzentration = true
wirkungsdauer = "bis zu 1 Stunde"
zeitaufwand = "1 Aktion"

[[zauber]]
name = "Alarm"
schule = "Bann"
stufe = 1
ritual = true
zeitaufwand = "1 Minute"
reichweite = "9m"
klassen = []
beschreibung = [
  "Du erschaffst einein Alarm gegen unerwünschtes Eindringen. W$hle eine Tür, ein Fenster oder einen Bereich in Reichweite, der nicht grösser als ein Würfel mit 6m Kantenlänge sein darf. Bis der Zauberspruch endet, macht dich ein Alarm darauf aufmerksam, wenn eine Kreatur der Grössenkategorie winzig oder grösser in den geschützten Bereich eindringt. Beim Wirken des Zaubers kannst du Kreaturen festlegen, die den Alarm nicht auslösen. Lege ausserdem fest, ob der Alarm geistig oder hörbar ist.",
  "Ein geistiger Alarm macht sich als Klingeln in deinem Kopf bemerkbar, wenn du dich innerhalb vom 1.5km um den geschützten bereich aufhälst. Das Klingeld weckt dich, falls du schlafen solltest.",
  "Ein hörbarer Alarm erzeugt im Umkreis von 18m für 10 Sekunden das Geräusch einer Handglocke.",
]
wirkungsdauer = "8 Stunden"
verbal = true
gesten = true
material = "eine winzige Glocke und ein Stück feinen Silberdrahts"

[[zauber]]
name = "Ansteckung"
schule = "Nekromantie"
stufe = 5
zeitaufwand = "1 Aktion"
reichweite = "Berührung"
verbal = true
gesten = true
wirkungsdauer = "7 Tage"
klassen = []
beschreibung = [
  "Deine Berührung löst Krankheiten aus. Führe deinen Nahkampf-Zauberangriff gegen eine Kreatur innerhalb deiner Reichweite aus. Bei einem Treffer wird das Ziel vergiftet",
  "Am Ende eines jeden seiner Züge muss das Ziel einen Konstitutionsrettungswurf ablegen. Gelingen drei dieser Rettungswürfe, ist das Ziel nicht länge vergiftet und der Zauber endet. Misslingen drei Würfe, ist das Ziel nicht länger vergiftet, du kannst aber eine der unten beschriebenen Krankheiten wählen. Diese Krankheit gilt bis zum Ende der Zauberwirkung.",
  "Da dieser Zauber das Ziel mit einer natürlichen Krankheit ansteckt, sind alle Effekte wirksam, die Krankheiten heilen oder anderseitig lindern.",
  "***Blendendes Siechtum:*** Schmerzen erfassen den Verstand der Kreatur und ihre Augen werden milchig weiss. Sie ist im Nachteil bei Weisheitswürfen sowie Weisheitsrettungswürfen und gilt als blind.",
  "***Fleischfäule:*** Das Fleisch der Kreatur verfault. Sie ist im Nachteil bei Charismawürfen und erhält eine Anfälligkeit gegenüber jeglichem Schaden.",
  "***Gedankenfeuer:*** Der Verstand der Kreatur wird vom Fieber verwirrt. Sie ist im Nachteil bei Intelligenzwürfen und Intelligenzrettungswürfen. Ausserdem verhält sich die Kreatur im Kampf, als würde sie unter den Auswirkungen des Zaubers *Verwirrung* leiden.",
  "***Krämpfe:*** Die Kreatur wird von Zitterkrämpfen erfasst. Sie ist im Nachteil bei Geschicklichkeitswürfen, Geschicklichkeitsrettungswürfen und Angriffswürfen, die Geschicklichkeit verwenden.",
  "***Schleimiges Verderben:*** Die Kreatur beginnt heftig zu bluten. Sie ist im Nachteil bei Konstitutionswürfen und Konstitutionsrettungswürfen. Ausserdem ist die Kreatur, immer wenn sie Schaden erleidet, bis zum Ende ihres nächsten Zuges betäubt.",
  "***Schmutzfieber:*** Ein rasendes Fieber schwächt den Körper der Kreatur. Sie ist im Nachteil bei Stärkewürfen, Stärkerettungswürfen und Angriffswürfen, die Stärke verwenden.",
]

[[zauber]]
name = "Antimagisches Feld"
schule = "Bann"
stufe = 8
zeitaufwand = "1 Aktion"
reichweite = "Selbst (Sphäre von 3m Radius)"
verbal = true
gesten = true
material = "eine Prise Eisenpulver oder Eisenspäne"
konzentration = true
wirkungsdauer = "bis zu eine Stunde"
klassen = []
beschreibung = [
  "Eine unsichtbare Kugel aus Antimagie mit 3m Radius umgibt dich. Dieser Bereich ist von der magischen Energie abgeschnitten, die das Multiversum erfüllt. Innerhalb der Sphäre können keine Zauber gewirkt werden, beschworene Kreaturen verschwinden und selbst magische Gegenstände werden zu gewöhnlichen. Bis der Zauber endet, bewegt sich die Sphäre mit dir als Mittelpunkt fort.",
  "Zauber und andere magische Effekte, mit Ausnahme solcher, die von einem Artefakt oder einer Gottheit erschaffen wurden, werden in der Sphäre unterdrückt und können nicht in sie eindringen. Ein Zauberplatz, der zum Wirken eines unterdrückten Zaubers verwendet wird, gilt als verbraucht. Solange ein Effekt unterdrückt ist, hat er keine Auswirkung. Der Zeitraum, in dem er unterdrückt wird, ist jedoch Teil seiner Wirkungsdauer.",
  "***Gezielte Effekte:*** Zauber und andere magische Effekte, wie Magisches Geschoss und Person bezaubern, die eine Kreatur oder einen Gegenstand in der Sphäre zum Ziel haben, beeinflussen ihr Ziel nicht.",
  "***Magische Flächeneffekte:*** Der Flächeneffekt eines Zaubers oder magischen Effekts, wie eines Feuerballs, kann nicht in die Sphäre eindringen. Wenn sich die Sphäre und ein magischer Flächeneffekt überschneiden, gilt der Teil des Flächeneffekts, der von der Sphäre bedeckt wird, als unterdrückt. Zum Beispiel werden die Flammen einer Feuerwand innerhalb der Sphäre unterdrückt, sodass eine Lücke in der Wand entsteht, wenn die Überschneidung groß genug ist.",
  "***Zauber:*** Alle aktiven Zauber oder anderen magischen Effekte, die eine Kreatur oder einen Gegenstand in der Sphäre beeinflussen, werden unterdrückt, solange sich die Kreatur oder der Gegenstand in der Sphäre befindet.",
  "***Magische Gegenstände:*** Die Eigenschaften und Kräfte von magischen Gegenständen werden in der Sphäre unterdrückt. Beispielsweise ist ein Langschwert +1 in der Sphäre nur ein ganz gewöhnliches Langschwert.",
  "***Magische Bewegung:*** Teleportation und Reisen durch die Ebenen funktionieren in der Sphäre nicht, gleichgültig ob die Sphäre das Ziel oder der Startpunkt dieser magischen Reise ist. Ein Portal an einen anderen Ort, eine Welt oder Existenzebene sowie Öffnungen in einen außerdimensionalen Raum, wie sie vom Zauber Seiltrick erschaffen werden, schließen sich für die Dauer, die sie sich in der Sphäre befinden.",
  "***Kreaturen und Gegenstände:*** Kreaturen oder Gegenstände, die auf magische Weise erschaffen oder beschworen wurden, hören in der Sphäre kurzzeitig auf zu existieren. Sie erscheinen sofort wieder, wenn der Ort, an dem sie sich zuletzt befanden, nicht mehr von der Sphäre bedeckt wird.",
  "***Magie bannen:*** Zauber und magische Effekte wie Magie bannen haben in der Sphäre keine Auswirkungen. Gleichermaßen können sich die Sphären, die von zwei verschiedenen Antimagischen Feldern erschaffen werden, nicht gegenseitig aufheben.",
]

[[zauber]]
name = "Antipathie/Sympathie"
schule = "Verzauberung"
stufe = 8
zeitaufwand = "1 Stunde"
reichweite = "18m"
verbal = true
gesten = true
material = "entweder ein mit Essig getr$nkter Brocken Alaun für den Antipathie-Effekt oder ein Tropfen Honig für den Sympathie-Effekt"
wirkungsdauer = "10 Tage"
klassen = []
beschreibung = [
  "Dieser Zauber zieht Kreaturen deiner Wahl an oder stößt sie ab. Du wirkst den Zauber auf etwas in Reichweite, entweder einen Gegenstand der Größenkategorie riesig oder kleiner oder einen Bereich, der nicht größer ist als ein Würfel mit 60m Kantenlänge. Dann bestimme eine Art von intelligenter Kreatur, wie rote Drachen, Goblins oder Vampire.",
  "Du erfüllst das Ziel mit einer Aura, welche die gewählten Kreaturen für die Wirkungsdauer entweder anzieht oder abstößt. Wähle Antipathie oder Sympathie für den Effekt der Aura.",
  "***Antipathie:*** Diese Verzauberung erfüllt Kreaturen der gewählten Art mit einem starken Drang, die Umgebung zu verlassen und das Ziel zu meiden. Wenn eine solche Kreatur das Ziel sehen kann oder sich in einen Umkreis von 18m um es begibt, muss ihr ein Weisheitsrettungswurf gelingen, um nicht verangstigt zu werden. Die Kreatur bleibt verängstigt, solange sie das Ziel sehen kann oder sich innerhalb des Radius von 18m befindet. Solange sie durch das Ziel verängstigt ist, muss sie ihre Bewegung verwenden, um sich an den nächsten sicheren Ort zu begeben, an dem sie das Ziel nicht sehen kann. Wenn sich die Kreatur mehr als 18m vom Ziel entfernt und es nicht mehr sehen kann, ist sie nicht länger verängstigt. Sie erhält den Zustand jedoch erneut, wenn sie das Ziel wieder sehen kann oder sich auf 18m oder weniger nähert.",
  "***Sympathie:*** Die Verzauberung sorgt dafür, dass Kreaturen der gewählten Art einen starken Drang verspüren, sich dem Ziel auf mindestens 18m zu nähern oder es zu sehen. Wenn eine solche Kreatur das Ziel sehen kann oder sich in einen Umkreis von 18m um es begibt, muss sie einen Weisheitsrettungswurf ablegen. Wenn dieser misslingt, muss sie ihre Bewegung in jedem ihrer Züge verwenden, um den Bereich zu betreten oder sich in Berührungsweite des Ziels zu begeben. Wenn die Kreatur dies getan hat, kann sie sich nicht willentlich vom Ziel entfernen.",
  "Wenn das Ziel eine beeinflusste Kreatur verletzt oder ihr anderweitig schadet, darf diese einen Weisheitsrettungswurf ablegen, um den Effekt zu beenden, wie es unten beschrieben ist.",
  "***Den Effekt beenden:*** Wenn sich eine beeinflusste Kreatur am Ende ihres Zuges außerhalb von 18m um das Ziel befindet und es nicht sehen kann, legt sie einen Weisheitsrettungswurf ab. Bei einem Erfolg ist die Kreatur nicht länger vom Effekt des Zaubers betroffen und begreift, dass das Gefühl der Abstoßung oder Anziehung magischer Natur ist. Außerdem darf eine Kreatur, die unter dem Einfluss dieses Zaubers steht (solange dieser wirkt), alle 24 Stunden einen weiteren Rettungswurf ablegen.",
  "Eine Kreatur, der ein Rettungswurf gegen den Effekt gelingt, ist für eine 1 Minute gegen seine Auswirkungen immun. Danach kann er wieder in Kraft treten.",
]

[[zauber]]
name = "Arkanes Auge"
schule = "Erkenntnis"
stufe = 4
zeitaufwand = "1 Aktion"
reichweite = "9m"
verbal = true
gesten = true
material = "etwas Fledermausfell"
konzentration = true
wirkungsdauer = "bis zu einer Stunde"
klassen = []
beschreibung = [
  "Du erschaffst ein unsichtbares, magisches Auge in Reichweite, das für die Wirkungsdauer in der Luft schwebt. Du erhältst auf geistige Weise visuelle Informationen von dem Auge, das über normale Sicht sowie eine Dunkelsicht von 9m verfügt. Das Auge kann in alle Richtungen blicken.",
  "Als Aktion kannst du das Auge 9m beliebig bewegen. Es darf sich von dir entfernen, aber nicht eine andere Ebene der Existenz betreten. Eine feste Barriere blockiert die Bewegung des Auges, es ist aber in der Lage, sich durch Öffnungen mit 2,5 cm Durchmesser zu zwängen.",
]

[[zauber]]
name = "Arkanes Schloss"
schule = "Bann"
stufe = 2
zeitaufwand = "1 Aktion"
reichweite = "Berührung"
verbal = true
gesten = true
material = "Goldstaub im Wert von mindestens 25GM, der beim Wirken des Zaubers verbraucht wird"
wirkungsdauer = "bis der Zauber gebannt wird"
klassen = []
beschreibung = [
  "Du berührst eine geschlossene Tür, ein Fenster, Tor, eine Kiste oder einen anderen Eingang, der für die Wirkungsdauer versiegelt wird. Du und andere Kreaturen, die du beim Wirken des Zaubers festlegst, können den Gegenstand normal öffnen. Du kannst auch ein Passwort festlegen, dass den Zauber für 1 Minute unterdrückt, wenn es innerhalb von 1,5m um den Gegenstand ausgesprochen wird. Ansonsten ist der Durchgang nicht zu passieren, bis er zerstört oder der Zauber gebannt wird. *Klopfen* auf den Gegenstand zu wirken, unterdrückt *Arkanes Schloss* für 10 Minuten.",
  "Solange der Gegenstand von diesem Zauber betroffen wird, ist er schwieriger zu zerstören oder aufzubrechen: Der SG eines Wurfes, um den Gegenstand zu zerbrechen oder zu knacken, steigt um 10.",
]
