import { cn } from "@/lib/utils";
import { Libre_Baskerville } from "next/font/google";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const serif = Libre_Baskerville({ weight: "400", subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className={cn(serif.className)}>{children}</div>;
}
